spin_manifest_version = 2

[application]
name = "challenge1"
version = "0.1.0"
authors = ["Nicolas Brassard <nicolasbrassard10401@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "challenge1"

[component.challenge1]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
route = "/data"
component = "data"

[component.data]
source = "data/target/wasm32-wasi/release/data.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.data.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "data"
watch = ["src/**/*.rs", "Cargo.toml"]
